### PR TITLE
chore: Release casper-sys

### PR DESCRIPTION
**Pull request by asomers**
I hope you approve this, because I already published the release.  But the repo's branch protection rules require a PR.

### CODE REVIEW

**Comment by asomers** [comment]
Actually, I think it's better if you temporarily relax the branch protection rules.  That way I can push to main and the pushed tag will match what I published.

**Comment by asomers** [comment]
ping @dlrobertson .  Could you please temporarily relax the branch protection rules so I can push the published tag?

**Review by dlrobertson — APPROVED** [review]

**Comment by dlrobertson** [comment]
> ping @dlrobertson . Could you please temporarily relax the branch protection rules so I can push the published tag?

done!

**Comment by asomers** [comment]
Whoa.  I pushed directly to main rather than merge the PR.  But github somehow detects this PR as being merged, even though there's no merge commit.  Anyway, thanks for helping @dlrobertson .  I'll make just one or two more changes and then publish capsicum itself.

**Pull request merged**
